### PR TITLE
fix primary setting for nic's ip_configuration block in vmss_linux.tf

### PR DESCRIPTION
**Pull request by rnfawcett**
# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Does this introduce a breaking change

- [ ] YES
- [ ] NO

### CODE REVIEW

**Comment by rnfawcett** [comment]
There is no need to determine the primary'ness of a NIC's IP Address when there's only 1 IP Address.  The primary setting of the NIC is not the same as the primary setting of the IP Address of a NIC.  They are 2 separate concepts.

**Review by rnfawcett — COMMENTED** [review]
Looks good

**Comment by rnfawcett** [comment]
@ghazalehca please merge after reviewing

**Review by ghazalehca — APPROVED** [review]
fixed the illogical primary problem

**Review by rnfawcett — COMMENTED** [review]
Looks good!

**Pull request merged**
